###Create new user
POST http://localhost:3000/api/signup
content-type: application/json

{
    "username": "master@gmail.com",
    "password": "password"
}

###Sign in user
POST http://localhost:3000/api/login
content-type: application/json

{
    "username": "master@gmail.com",
    "password": "password"
}

###Sign out user
POST http://localhost:3000/api/signout

###Create new invoice
POST http://localhost:3000/api/newinvoice
content-type: application/json

{
    "userId": 1,
    "amount": 200,
    "date": "2-3-2024",
    "purpose": "built a patio"
}

###Email invoice
POST http://localhost:3000/api/email/1
content-type: application/json

{
    "email": "matthewdelabastide@murphyclarke.com"
}

###Update receipt pdfs
POST http://localhost:3000/api/create-receipts

###Upload receipts to Azure
POST http://localhost:3000/api/upload-receipts

###Input receipt data
POST http://localhost:3000/api/input
content-type: application/json

{
    "date": "2-3-2024",
    "customerName": "John Doe",
    "paymentMethod": "Cash",
    "amount": "200",
    "address": "1234 Main St"
}

###Create and upload receipts
GET http://localhost:3000/api/num-receipts

###Get identification URL and SAS token
GET http://localhost:3000/api/identification